### ISSUE TITLE
Fix styling of nav bar on detail pages

### ISSUE THREAD

**Issue by fishcharlie** [gregbrunk/fourteeners#1]
On detail pages nav bar is transparent when you scroll down so it's really hard to see the text on a white background.

<img width="1379" alt="screen shot 2016-07-22 at 2 11 08 pm" src="https://cloud.githubusercontent.com/assets/860375/17069862/2bf777da-5016-11e6-82a2-a513b19ce8ad.png">

**Comment by gregbrunk** [comment]
Fixed!
